molesol:
    epoch: 150
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.8
    t: 0.2
mollipo:
    epoch: 50
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.8
    t: 0.2
molfreesolv:
    epoch: 20
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.8
    t: 0.2
molbace:
    epoch: 80
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.8
    t: 0.2
molbbbp:
    epoch: 20
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.8
    t: 0.2
molclintox:
    epoch: 50
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.8
    t: 0.2
moltox21:
    epoch: 50
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.8
    t: 0.2
molsider:
    epoch: 50
    lr: 0.0001
    weight_decay: 0.00001
    batch_size: 32
    hidden_dim: 300
    period: 10
    pooling: 'add'
    spa_layer: 5
    spe_layer: 2
    spa_dropout: 0.5
    spe_dropout: 0.5
    t: 0.2
